import { NextRequest, NextResponse } from 'next/server';
import { checkRateLimit, RATE_LIMITS } from '@/lib/rate-limit';
import { db } from '@/lib/db';
import { requireAuth } from '@/lib/session';

/* ──────────────────────────────────────────────────────────────────
   /api/diary — Ramadan Diary
   GET  returns diary entries
   POST creates a new diary entry
   ────────────────────────────────────────────────────────────────── */

type Mood = 'blessed' | 'happy' | 'neutral' | 'tired' | 'grateful';

interface DiaryEntryShape {
  id: string;
  date: string;
  text: string;
  mood: Mood;
  orderId?: string;
  autoGenerated?: boolean;
  tags?: string[];
}

// Fallback mock data
const MOCK_ENTRIES: DiaryEntryShape[] = [
  {
    id: 'de1',
    date: '2026-02-18',
    text: 'First day of Ramadan! Alhamdulillah, started with a beautiful sahur. Made oats and dates.',
    mood: 'blessed',
    autoGenerated: false,
    tags: ['Sahur', 'Prayer'],
  },
  {
    id: 'de2',
    date: '2026-02-19',
    text: 'Ordered Jollof Rice from The Food Hub for iftar. Broke fast with dates and water first.',
    mood: 'happy',
    orderId: 'ORD-001',
    autoGenerated: true,
    tags: ['Iftar'],
  },
  {
    id: 'de3',
    date: '2026-02-20',
    text: 'Read 2 pages of Quran after Tarawih. Feeling grateful for this blessed month.',
    mood: 'grateful',
    autoGenerated: false,
    tags: ['Quran', 'Prayer', 'Gratitude'],
  },
];

export async function GET() {
  try {
    const dbEntries = await db.diaryEntry.findMany({
      orderBy: { date: 'asc' },
    });

    if (dbEntries.length > 0) {
      const entries: DiaryEntryShape[] = dbEntries.map(e => ({
        id: e.id,
        date: e.date,
        text: e.text,
        mood: (e.mood as Mood) || 'neutral',
        orderId: e.orderId || undefined,
        autoGenerated: !!e.orderId,
        tags: JSON.parse(e.tags || '[]'),
      }));
      return NextResponse.json({ entries });
    }
  } catch {
    // Fallback to mock
  }

  return NextResponse.json({ entries: MOCK_ENTRIES });
}

export async function POST(req: NextRequest) {
  const rateLimitResponse = await checkRateLimit(req, RATE_LIMITS.write);
  if (rateLimitResponse) return rateLimitResponse;
  
  // REQUIRE AUTHENTICATION - diary entries are private
  const auth = await requireAuth(req);
  if (auth instanceof NextResponse) return auth;
  
  try {
    const body = await req.json();
    const { date, text, mood, tags, orderId } = body as {
      date?: string;
      text?: string;
      mood?: Mood;
      tags?: string[];
      orderId?: string;
    };
    
    // Use authenticated user's ID
    const userId = auth.userId;

    if (!date || !text) {
      return NextResponse.json(
        { error: 'Date and text are required' },
        { status: 400 }
      );
    }

    const validMoods: Mood[] = ['blessed', 'happy', 'neutral', 'tired', 'grateful'];
    const entryMood: Mood = mood && validMoods.includes(mood) ? mood : 'neutral';

    // Write to DB
    let entry;
    try {
      entry = await db.diaryEntry.upsert({
        where: { userId_date: { userId, date } },
        update: { text, mood: entryMood, orderId, tags: JSON.stringify(tags || []) },
        create: { userId, date, text, mood: entryMood, orderId, tags: JSON.stringify(tags || []) },
      });
    } catch {
      // Fallback in-memory
      entry = {
        id: `de-${Date.now()}`,
        date,
        text,
        mood: entryMood,
        orderId,
        tags: JSON.stringify(tags || []),
      };
    }

    const newEntry: DiaryEntryShape = {
      id: entry.id,
      date: entry.date,
      text: entry.text,
      mood: (entry.mood as Mood) || 'neutral',
      orderId: entry.orderId || undefined,
      autoGenerated: !!entry.orderId,
      tags: JSON.parse(entry.tags || '[]'),
    };

    return NextResponse.json({ entry: newEntry }, { status: 201 });
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }
}
