import { NextResponse } from 'next/server';

const products = [
  {
    id: 1,
    name: "The Ultimate Ramadan Box",
    description: "Curated Iftar & Sahur essentials box filled with premium rice, cooking oil, dates, fruits, and spices to keep you and your family energized throughout the blessed month.",
    originalPrice: 25000,
    salePrice: 17500,
    category: "bundles",
    rating: 4.9,
    reviews: 234,
    deliveryTime: "25-35 min",
    inStock: true,
    image: "/images/products/ramadan-box-1.png",
    images: [
      "/images/products/ramadan-box-1.png",
      "/images/products/ramadan-box-2.png",
      "/images/products/ramadan-box-3.png",
      "/images/products/ramadan-box-4.png",
    ],
    contents: "12 Premium Items",
  },
  {
    id: 2,
    name: "Jollof Rice & Chicken",
    description: "Smoky party jollof with succulent grilled chicken. A Lagos classic!",
    price: 4500,
    category: "meals",
    rating: 4.9,
    reviews: 289,
    deliveryTime: "25 min",
    inStock: true,
    image: "/images/meals/meal-jollof.png",
    images: ["/images/meals/meal-jollof.png"],
  },
  {
    id: 3,
    name: "Suya Platter",
    description: "Spicy beef suya with fresh onions and tomatoes. A Lagos street food classic.",
    price: 3200,
    category: "meals",
    rating: 4.8,
    reviews: 203,
    deliveryTime: "30 min",
    inStock: true,
    image: "/images/meals/meal-suya.png",
    images: ["/images/meals/meal-suya.png"],
  },
  {
    id: 4,
    name: "Moi Moi & Pap",
    description: "Steamed bean pudding with creamy corn pap. Perfect for Sahur.",
    price: 2800,
    category: "meals",
    rating: 4.7,
    reviews: 156,
    deliveryTime: "20 min",
    inStock: true,
    image: "/images/meals/meal-moimoi.png",
    images: ["/images/meals/meal-moimoi.png"],
  },
  {
    id: 5,
    name: "Date & Nut Smoothie",
    description: "Energy-packed date smoothie with groundnuts. Great for Iftar or Sahur.",
    price: 1800,
    category: "drinks",
    rating: 4.9,
    reviews: 178,
    deliveryTime: "15 min",
    inStock: true,
    image: "/images/meals/meal-smoothie.png",
    images: ["/images/meals/meal-smoothie.png"],
  },
  {
    id: 6,
    name: "Premium Dates Box",
    description: "Premium Ajwa and Medjool dates. Perfect for breaking your fast.",
    originalPrice: 12000,
    salePrice: 7500,
    category: "bundles",
    rating: 4.7,
    reviews: 98,
    deliveryTime: "20-25 min",
    inStock: true,
    image: "/images/flash-sales/flash-dates.png",
    images: ["/images/flash-sales/flash-dates.png"],
  },
  {
    id: 7,
    name: "Iftar Family Bundle",
    description: "Complete Iftar meal for the whole family. Serves 6.",
    originalPrice: 18000,
    salePrice: 11000,
    category: "bundles",
    rating: 4.8,
    reviews: 142,
    deliveryTime: "30-40 min",
    inStock: true,
    image: "/images/flash-sales/flash-iftar-bundle.png",
    images: ["/images/flash-sales/flash-iftar-bundle.png"],
  },
  {
    id: 8,
    name: "Zobo & Kunu Pack",
    description: "Traditional hibiscus and millet drinks. Refreshing and nutritious.",
    originalPrice: 5000,
    salePrice: 2800,
    category: "drinks",
    rating: 4.6,
    reviews: 67,
    deliveryTime: "15-20 min",
    inStock: true,
    image: "/images/flash-sales/flash-zobo-kunu.png",
    images: ["/images/flash-sales/flash-zobo-kunu.png"],
  },
];

export async function GET() {
  return NextResponse.json({ products });
}
