#!/bin/bash
set -euo pipefail

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SwiftRamadan — One-Click Production Bootstrap
# Sets up a fresh Ubuntu server with everything needed to run the app
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#
# Usage: curl -fsSL https://your-server/bootstrap.sh | bash
#    OR: ./scripts/bootstrap-production.sh
#
# Prerequisites: Fresh Ubuntu 22.04 LTS server with root access
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

echo "🚀 SwiftRamadan Production Bootstrap"
echo "====================================="
echo ""

# ── Step 1: System Update ──
echo "📦 Step 1/8: Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq
echo "  ✅ System updated"

# ── Step 2: Install Docker ──
echo ""
echo "📦 Step 2/8: Installing Docker..."
if command -v docker >/dev/null 2>&1; then
  echo "  ✅ Docker already installed"
else
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  echo "  ✅ Docker installed"
fi

# ── Step 3: Install Docker Compose ──
echo ""
echo "📦 Step 3/8: Installing Docker Compose..."
if docker compose version >/dev/null 2>&1; then
  echo "  ✅ Docker Compose already available"
else
  apt-get install -y docker-compose-plugin 2>/dev/null || {
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" \
      -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  }
  echo "  ✅ Docker Compose installed"
fi

# ── Step 4: Create App Directory ──
echo ""
echo "📦 Step 4/8: Setting up app directory..."
APP_DIR="/opt/swiftramadan"
mkdir -p "$APP_DIR"
echo "  ✅ App directory: $APP_DIR"

# ── Step 5: Generate Secrets ──
echo ""
echo "🔐 Step 5/8: Generating production secrets..."
APP_SECRET=$(openssl rand -base64 48)
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
echo "  ✅ Secrets generated"

# ── Step 6: Create .env File ──
echo ""
echo "📝 Step 6/8: Creating .env configuration..."
cat > "$APP_DIR/.env" << ENVEOF
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SwiftRamadan — Production Environment
# Auto-generated by bootstrap-production.sh
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ── Required ──
NODE_ENV=production
APP_SECRET=${APP_SECRET}
NEXT_PUBLIC_APP_URL=https://swiftramadan.com
DATABASE_URL=postgresql://swiftramadan:${DB_PASSWORD}@postgres:5432/swiftramadan?schema=public

# ── Docker Compose ──
DB_PASSWORD=${DB_PASSWORD}

# ── CORS ──
CORS_ALLOWED_ORIGINS=https://swiftramadan.com,https://www.swiftramadan.com

# ── Payment Providers (add your keys below) ──
# PAYSTACK_SECRET_KEY=
# PAYSTACK_PUBLIC_KEY=
# FLUTTERWAVE_SECRET_KEY=
# FLUTTERWAVE_PUBLIC_KEY=

# ── AI Services ──
# ZAI_API_KEY=

# ── Communication ──
# RESEND_API_KEY=
# TERMII_API_KEY=

# ── OAuth ──
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=

# ── Storage ──
# CLOUDINARY_CLOUD_NAME=
# CLOUDINARY_API_KEY=
# CLOUDINARY_API_SECRET=

# ── Maps ──
# GOOGLE_MAPS_API_KEY=
ENVEOF
chmod 600 "$APP_DIR/.env"
echo "  ✅ .env created at $APP_DIR/.env"

# ── Step 7: Setup SSL with Let's Encrypt ──
echo ""
echo "🔒 Step 7/8: SSL certificate setup..."
echo "  ⚠️  SSL requires a domain name pointing to this server."
echo "  After pointing your DNS, run:"
echo "  apt-get install -y certbot"
echo "  certbot certonly --standalone -d swiftramadan.com -d www.swiftramadan.com"
echo "  mkdir -p $APP_DIR/ssl"
echo "  cp /etc/letsencrypt/live/swiftramadan.com/fullchain.pem $APP_DIR/ssl/"
echo "  cp /etc/letsencrypt/live/swiftramadan.com/privkey.pem $APP_DIR/ssl/"
echo ""

# ── Step 8: Ready to Deploy ──
echo ""
echo "🚀 Step 8/8: Ready to deploy!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Copy your source code to $APP_DIR/"
echo "     git clone <your-repo> $APP_DIR"
echo "     OR: scp -r ./ $APP_DIR"
echo ""
echo "  2. Edit $APP_DIR/.env with your real API keys"
echo "     nano $APP_DIR/.env"
echo ""
echo "  3. Set up SSL (see Step 7 above)"
echo ""
echo "  4. Build and start:"
echo "     cd $APP_DIR"
echo "     docker compose up -d --build"
echo ""
echo "  5. Run migrations:"
echo "     docker compose exec app npx prisma migrate deploy"
echo ""
echo "  6. Check health:"
echo "     curl http://localhost/api/health"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔑 Your generated secrets (SAVE THESE!):"
echo "  APP_SECRET=$APP_SECRET"
echo "  DB_PASSWORD=$DB_PASSWORD"
echo ""
echo "✅ Bootstrap complete!"
