'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Calendar,
  PenLine,
  Smile,
  Meh,
  Frown,
  Heart,
  BookOpen,
  Share2,
  ChevronLeft,
  ChevronRight,
  Plus,
  Moon,
  Star,
  Utensils,
  Clock,
  Sparkles,
  Check,
} from 'lucide-react';
import { useNavigation, useUserName, useDiary } from '@/lib/store-selectors';
import { useToast } from '@/hooks/use-toast';

/* ──────────────────────────────────────────────────────────────────
   RamadanDiary — Private journal with calendar view, mood tracking,
   auto-entries from orders/meals. End-of-Ramadan shareable card.
   ────────────────────────────────────────────────────────────────── */

type Mood = 'blessed' | 'happy' | 'neutral' | 'tired' | 'grateful';

interface DiaryEntry {
  id: string;
  date: string; // YYYY-MM-DD
  text: string;
  mood: Mood;
  orderId?: string;
  autoGenerated?: boolean;
  tags?: string[];
}

interface DayData {
  date: string;
  hasEntry: boolean;
  mood?: Mood;
  isToday: boolean;
  isRamadan: boolean;
}

const MOODS: { value: Mood; label: string; icon: typeof Smile; color: string }[] = [
  { value: 'blessed', label: 'Blessed', icon: Star, color: '#F5C451' },
  { value: 'happy', label: 'Happy', icon: Smile, color: '#10E07A' },
  { value: 'grateful', label: 'Grateful', icon: Heart, color: '#A78BFA' },
  { value: 'neutral', label: 'Neutral', icon: Meh, color: '#38BDF8' },
  { value: 'tired', label: 'Tired', icon: Frown, color: '#F59E0B' },
];

const TAGS = ['Iftar', 'Sahur', 'Prayer', 'Quran', 'Family', 'Fasting', 'Reflection', 'Gratitude'];

const RAMADAN_START = '2026-02-18';
const RAMADAN_END = '2026-03-19';
const RAMADAN_DAYS = 30;

/* Seed some diary entries */
const MOCK_ENTRIES: DiaryEntry[] = [
  {
    id: 'de1',
    date: '2026-02-18',
    text: 'First day of Ramadan! Alhamdulillah, started with a beautiful sahur. Made oats and dates.',
    mood: 'blessed',
    autoGenerated: false,
    tags: ['Sahur', 'Prayer'],
  },
  {
    id: 'de2',
    date: '2026-02-19',
    text: 'Ordered Jollof Rice from The Food Hub for iftar. Broke fast with dates and water first. 🌙',
    mood: 'happy',
    orderId: 'ORD-001',
    autoGenerated: true,
    tags: ['Iftar'],
  },
  {
    id: 'de3',
    date: '2026-02-20',
    text: 'Read 2 pages of Quran after Tarawih. Feeling grateful for this blessed month.',
    mood: 'grateful',
    autoGenerated: false,
    tags: ['Quran', 'Prayer', 'Gratitude'],
  },
  {
    id: 'de4',
    date: '2026-02-22',
    text: 'Pepper soup and plantain for iftar. A bit tired today but still fasting, alhamdulillah.',
    mood: 'tired',
    autoGenerated: false,
    tags: ['Iftar', 'Reflection'],
  },
  {
    id: 'de5',
    date: '2026-02-24',
    text: 'Family iftar gathering! Made a big pot of jollof and everyone came over.',
    mood: 'blessed',
    autoGenerated: false,
    tags: ['Iftar', 'Family', 'Gratitude'],
  },
  {
    id: 'de6',
    date: '2026-02-27',
    text: 'Sahur: Moi moi and pap. Quick and filling. 🤲',
    mood: 'neutral',
    autoGenerated: false,
    tags: ['Sahur'],
  },
];

function RamadanDiaryInner() {
  const { activeModal, setActiveModal } = useNavigation();
  const userName = useUserName();
  const { diaryEntries, addDiaryEntry } = useDiary();
  const isOpen = activeModal === 'ramadan-diary';
  const { toast } = useToast();

  const [entries, setEntries] = useState<DiaryEntry[]>(MOCK_ENTRIES);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [showShareable, setShowShareable] = useState(false);
  const [currentMonth, setCurrentMonth] = useState(2); // March (0-indexed from Date)
  const [currentYear, setCurrentYear] = useState(2026);

  // Create form state
  const [newText, setNewText] = useState('');
  const [newMood, setNewMood] = useState<Mood>('happy');
  const [newTags, setNewTags] = useState<string[]>([]);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const res = await fetch('/api/diary');
        if (res.ok && !cancelled) {
          const data = await res.json();
          if (data.entries && data.entries.length > 0) {
            setEntries(data.entries);
          }
        }
      } catch {
        // keep local data
      }
    }
    load();
    return () => { cancelled = true; };
  }, []);

  /* ── Sync with Zustand store ── */
  useEffect(() => {
    diaryEntries.forEach((de) => {
      if (!entries.find((e) => e.date === de.date && e.text === de.text)) {
        setEntries((prev) => [
          ...prev,
          {
            id: `store-${Date.now()}-${Math.random()}`,
            date: de.date,
            text: de.text,
            mood: 'neutral',
            orderId: de.orderId,
            autoGenerated: !!de.orderId,
          },
        ]);
      }
    });
  }, [diaryEntries, entries]);

  /* ── Escape key handler ── */
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (showCreate) setShowCreate(false);
        else if (showShareable) setShowShareable(false);
        else if (selectedDate) setSelectedDate(null);
      }
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [showCreate, showShareable, selectedDate]);

  /* ── Calendar helpers ── */
  const getDaysInMonth = (year: number, month: number) => new Date(year, month + 1, 0).getDate();
  const getFirstDayOfMonth = (year: number, month: number) => new Date(year, month, 1).getDay();

  const today = new Date();
  const todayStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;

  const generateCalendarDays = (): DayData[] => {
    const daysInMonth = getDaysInMonth(currentYear, currentMonth);
    const days: DayData[] = [];

    for (let d = 1; d <= daysInMonth; d++) {
      const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
      const entry = entries.find((e) => e.date === dateStr);
      days.push({
        date: dateStr,
        hasEntry: !!entry,
        mood: entry?.mood,
        isToday: dateStr === todayStr,
        isRamadan: dateStr >= RAMADAN_START && dateStr <= RAMADAN_END,
      });
    }
    return days;
  };

  const calendarDays = generateCalendarDays();
  const firstDayOffset = getFirstDayOfMonth(currentYear, currentMonth);
  const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

  /* ── Selected date entries ── */
  const selectedEntries = selectedDate
    ? entries.filter((e) => e.date === selectedDate)
    : [];

  /* ── Stats for shareable card ── */
  const totalEntries = entries.length;
  const moodCounts = entries.reduce((acc, e) => {
    acc[e.mood] = (acc[e.mood] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  const topMood = Object.entries(moodCounts).sort((a, b) => b[1] - a[1])[0];
  const daysWithEntry = new Set(entries.map((e) => e.date)).size;
  const totalTags = entries.reduce((acc, e) => acc + (e.tags?.length || 0), 0);
  const ramadanProgress = Math.min(
    Math.round((daysWithEntry / RAMADAN_DAYS) * 100),
    100
  );

  /* ── Mood icon helper ── */
  const getMoodIcon = (mood: Mood) => {
    const m = MOODS.find((mo) => mo.value === mood);
    if (!m) return <Meh className="w-4 h-4 text-white/65" />;
    const Icon = m.icon;
    return <Icon className="w-4 h-4" style={{ color: m.color }} />;
  };

  const getMoodColor = (mood?: Mood) => {
    const m = MOODS.find((mo) => mo.value === mood);
    return m?.color || '#666';
  };

  /* ── Create entry ── */
  const handleCreateEntry = async () => {
    if (!newText.trim()) {
      toast({ title: 'Write something', description: 'Add a diary entry for this day' });
      return;
    }

    const date = selectedDate || todayStr;
    const newEntry: DiaryEntry = {
      id: `de-${Date.now()}`,
      date,
      text: newText,
      mood: newMood,
      autoGenerated: false,
      tags: newTags,
    };

    try {
      const res = await fetch('/api/diary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date,
          text: newText,
          mood: newMood,
          tags: newTags,
        }),
      });
      if (res.ok) {
        const data = await res.json();
        if (data.entry) newEntry.id = data.entry.id;
      }
    } catch {
      // still add locally
    }

    setEntries((prev) => [...prev, newEntry]);
    addDiaryEntry({ date, text: newText, orderId: undefined });

    setShowCreate(false);
    setNewText('');
    setNewMood('happy');
    setNewTags([]);
    toast({ title: 'Entry saved! 📖', description: 'Your Ramadan diary has been updated' });
  };

  /* ── Tag toggle ── */
  const toggleTag = (tag: string) => {
    setNewTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag]
    );
  };

  if (!isOpen) return null;

  return (
    <div className="w-full space-y-4">
      {/* ── Header ── */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <BookOpen className="w-5 h-5 text-[var(--sr-ai)]" />
          <h2 className="text-white font-semibold text-lg">Ramadan Diary</h2>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowShareable(true)}
            className="bg-[var(--sr-ai)]/10 border border-[var(--sr-ai)]/30 text-[var(--sr-ai)] text-xs font-semibold px-3 py-1.5 rounded-full flex items-center gap-1 hover:bg-[var(--sr-ai)]/20 transition-colors"
          >
            <Share2 className="w-3.5 h-3.5" /> My Ramadan
          </button>
          <button
            onClick={() => {
              setSelectedDate(todayStr);
              setShowCreate(true);
            }}
            className="bg-[var(--sr-customer)] text-black text-xs font-semibold px-3 py-1.5 rounded-full flex items-center gap-1 hover:bg-[var(--sr-customer)]/90 transition-colors"
          >
            <Plus className="w-3.5 h-3.5" /> Entry
          </button>
        </div>
      </div>

      {/* ── Quick Stats ── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2">
        <div className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-xl p-3 text-center">
          <p className="text-[var(--sr-customer)] text-lg font-bold">{daysWithEntry}</p>
          <p className="text-white/65 text-[10px]">Days Logged</p>
        </div>
        <div className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-xl p-3 text-center">
          <p className="text-[var(--sr-vendor)] text-lg font-bold">{totalEntries}</p>
          <p className="text-white/65 text-[10px]">Total Entries</p>
        </div>
        <div className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-xl p-3 text-center">
          <p className="text-[var(--sr-ai)] text-lg font-bold">{ramadanProgress}%</p>
          <p className="text-white/65 text-[10px]">Progress</p>
        </div>
      </div>

      {/* ── Calendar View ── */}
      <div className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-xl p-3 sm:p-4">
        {/* Month Navigation */}
        <div className="flex items-center justify-between mb-4">
          <button
            onClick={() => {
              if (currentMonth === 0) {
                setCurrentMonth(11);
                setCurrentYear((y) => y - 1);
              } else {
                setCurrentMonth((m) => m - 1);
              }
            }}
            className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-colors"
            aria-label="Previous month"
          >
            <ChevronLeft className="w-4 h-4 text-white/60" />
          </button>
          <h3 className="text-white font-semibold text-sm">
            {monthNames[currentMonth]} {currentYear}
          </h3>
          <button
            onClick={() => {
              if (currentMonth === 11) {
                setCurrentMonth(0);
                setCurrentYear((y) => y + 1);
              } else {
                setCurrentMonth((m) => m + 1);
              }
            }}
            className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-colors"
            aria-label="Next month"
          >
            <ChevronRight className="w-4 h-4 text-white/60" />
          </button>
        </div>

        {/* Day Headers */}
        <div className="grid grid-cols-7 gap-1 mb-2">
          {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((d) => (
            <div key={d} className="text-center text-white/60 text-[10px] py-1">
              {d}
            </div>
          ))}
        </div>

        {/* Calendar Grid */}
        <div className="grid grid-cols-7 gap-1">
          {/* Empty cells for offset */}
          {Array.from({ length: firstDayOffset }).map((_, i) => (
            <div key={`empty-${i}`} className="aspect-square" />
          ))}

          {calendarDays.map((day) => (
            <motion.button
              key={day.date}
              whileTap={{ scale: 0.9 }}
              onClick={() => setSelectedDate(day.date)}
              className={`aspect-square rounded-lg flex flex-col items-center justify-center relative transition-all ${
                selectedDate === day.date
                  ? 'bg-[var(--sr-customer)]/20 border border-[var(--sr-customer)]/50'
                  : day.isToday
                    ? 'bg-[var(--sr-vendor)]/10 border border-[var(--sr-vendor)]/30'
                    : day.isRamadan && day.hasEntry
                      ? 'bg-white/5 hover:bg-white/10'
                      : day.isRamadan
                        ? 'hover:bg-white/5'
                        : ''
              }`}
              aria-label={`${day.date}${day.hasEntry ? ' - has entry' : ''}`}
            >
              <span
                className={`text-xs ${
                  day.isToday
                    ? 'text-[var(--sr-vendor)] font-bold'
                    : day.hasEntry
                      ? 'text-white'
                      : 'text-white/60'
                }`}
              >
                {day.date.split('-')[2]?.replace(/^0/, '')}
              </span>
              {day.hasEntry && day.mood && (
                <span
                  className="w-1.5 h-1.5 rounded-full mt-0.5"
                  style={{ backgroundColor: getMoodColor(day.mood) }}
                />
              )}
              {day.isRamadan && !day.hasEntry && (
                <Moon className="w-2 h-2 text-white/15" />
              )}
            </motion.button>
          ))}
        </div>

        {/* Legend */}
        <div className="flex items-center gap-3 mt-3 flex-wrap">
          {MOODS.map((m) => {
            const Icon = m.icon;
            return (
              <div key={m.value} className="flex items-center gap-1">
                <Icon className="w-3 h-3" style={{ color: m.color }} />
                <span className="text-white/60 text-[9px]">{m.label}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* ── Selected Date Entries ── */}
      <AnimatePresence mode="wait">
        {selectedDate && (
          <motion.div
            key={selectedDate}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="space-y-3"
          >
            <div className="flex items-center justify-between">
              <h3 className="text-white/70 text-sm font-medium flex items-center gap-2">
                <Calendar className="w-4 h-4" />
                {selectedDate}
              </h3>
              <button
                onClick={() => {
                  setShowCreate(true);
                }}
                className="text-[var(--sr-customer)] text-xs flex items-center gap-1 hover:text-[var(--sr-customer)]/80"
              >
                <Plus className="w-3 h-3" /> Add Entry
              </button>
            </div>

            {selectedEntries.length === 0 ? (
              <div className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-xl p-6 text-center">
                <Moon className="w-8 h-8 text-white/15 mx-auto mb-2" />
                <p className="text-white/60 text-sm">No entries for this day</p>
                <button
                  onClick={() => setShowCreate(true)}
                  className="mt-2 text-[var(--sr-customer)] text-xs hover:underline"
                >
                  Write one now →
                </button>
              </div>
            ) : (
              <div className="space-y-2">
                {selectedEntries.map((entry) => (
                  <motion.div
                    key={entry.id}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-xl p-3 sm:p-4"
                  >
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center gap-2">
                        {getMoodIcon(entry.mood)}
                        <span className="text-white/60 text-xs capitalize">{entry.mood}</span>
                        {entry.autoGenerated && (
                          <span className="text-[10px] text-[var(--sr-rider)] bg-[var(--sr-rider)]/10 px-1.5 py-0.5 rounded-full">
                            Auto
                          </span>
                        )}
                      </div>
                      {entry.orderId && (
                        <span className="text-white/60 text-[10px] flex items-center gap-1">
                          <Utensils className="w-3 h-3" /> {entry.orderId}
                        </span>
                      )}
                    </div>
                    <p className="text-white/80 text-sm leading-relaxed">{entry.text}</p>
                    {entry.tags && entry.tags.length > 0 && (
                      <div className="flex gap-1 mt-2 flex-wrap">
                        {entry.tags.map((tag) => (
                          <span
                            key={tag}
                            className="text-[10px] text-white/65 bg-white/5 px-2 py-0.5 rounded-full"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    )}
                  </motion.div>
                ))}
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Create Entry Modal ── */}
      <AnimatePresence>
        {showCreate && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-[var(--sr-surface-base)]/95 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4"
            role="dialog"
            aria-modal="true"
            aria-label="Create diary entry"
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-2xl w-full max-w-md max-h-[90vh] overflow-y-auto"
            >
              <div className="flex items-center justify-between p-3 sm:p-4 border-b border-white/8">
                <h2 className="text-white font-semibold text-lg flex items-center gap-2">
                  <PenLine className="w-5 h-5 text-[var(--sr-ai)]" /> Diary Entry
                </h2>
                <button
                  onClick={() => setShowCreate(false)}
                  className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center"
                  aria-label="Close"
                >
                  <X className="w-4 h-4 text-white" />
                </button>
              </div>

              <div className="p-4 space-y-4">
                {/* Date */}
                <div>
                  <label className="text-white/60 text-xs block mb-1">Date</label>
                  <div className="bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-white/70 text-sm flex items-center gap-2">
                    <Calendar className="w-4 h-4 text-white/60" />
                    {selectedDate || todayStr}
                  </div>
                </div>

                {/* Mood */}
                <div>
                  <label className="text-white/60 text-xs block mb-2">How are you feeling?</label>
                  <div className="flex gap-2">
                    {MOODS.map((m) => {
                      const Icon = m.icon;
                      return (
                        <button
                          key={m.value}
                          onClick={() => setNewMood(m.value)}
                          className={`flex-1 flex flex-col items-center gap-1 py-2 rounded-xl transition-all ${
                            newMood === m.value
                              ? 'bg-white/10 border border-white/20'
                              : 'bg-white/3 hover:bg-white/5'
                          }`}
                          aria-label={`Mood: ${m.label}`}
                        >
                          <Icon
                            className="w-5 h-5"
                            style={{ color: newMood === m.value ? m.color : '#666' }}
                          />
                          <span
                            className="text-[9px]"
                            style={{ color: newMood === m.value ? m.color : '#666' }}
                          >
                            {m.label}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>

                {/* Entry Text */}
                <div>
                  <label className="text-white/60 text-xs block mb-1">Your thoughts</label>
                  <textarea
                    value={newText}
                    onChange={(e) => setNewText(e.target.value)}
                    placeholder="How was your day of fasting? What are you grateful for?"
                    rows={4}
                    className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-white text-sm placeholder:text-white/60 focus:outline-none focus:border-[var(--sr-ai)]/50 resize-none"
                  />
                </div>

                {/* Tags */}
                <div>
                  <label className="text-white/60 text-xs block mb-2">Tags</label>
                  <div className="flex flex-wrap gap-2">
                    {TAGS.map((tag) => (
                      <button
                        key={tag}
                        onClick={() => toggleTag(tag)}
                        className={`px-3 py-1 rounded-full text-xs transition-all flex items-center gap-1 ${
                          newTags.includes(tag)
                            ? 'bg-[var(--sr-ai)]/20 text-[var(--sr-ai)] border border-[var(--sr-ai)]/30'
                            : 'bg-white/5 text-white/65 hover:bg-white/10'
                        }`}
                      >
                        {newTags.includes(tag) && <Check className="w-3 h-3" />}
                        {tag}
                      </button>
                    ))}
                  </div>
                </div>

                <button
                  onClick={handleCreateEntry}
                  className="w-full bg-[var(--sr-customer)] text-black font-semibold py-3 rounded-xl flex items-center justify-center gap-2 hover:bg-[var(--sr-customer)]/90 transition-colors"
                >
                  <BookOpen className="w-4 h-4" /> Save Entry
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Shareable "My Ramadan 2026" Card ── */}
      <AnimatePresence>
        {showShareable && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-[var(--sr-surface-base)]/95 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4"
            role="dialog"
            aria-modal="true"
            aria-label="My Ramadan 2026 shareable card"
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-[var(--sr-surface-raised)] border border-white/8 rounded-2xl w-full max-w-sm overflow-hidden"
            >
              {/* Shareable Card */}
              <div className="relative bg-gradient-to-br from-[#0B0D14] via-[#0F1118] to-[#0B0D14] p-6 overflow-hidden">
                {/* Decorative elements */}
                <div className="absolute top-0 right-0 w-32 h-32 bg-[var(--sr-customer)]/5 rounded-full blur-3xl" />
                <div className="absolute bottom-0 left-0 w-24 h-24 bg-[var(--sr-ai)]/5 rounded-full blur-3xl" />
                <div className="absolute top-4 right-4 text-[var(--sr-vendor)]/20 text-6xl">🌙</div>

                <div className="relative z-10 space-y-4">
                  {/* Title */}
                  <div className="text-center">
                    <h3 className="text-[var(--sr-vendor)] text-xs font-semibold tracking-widest uppercase mb-1">
                      My Ramadan
                    </h3>
                    <h2 className="text-white text-2xl font-bold">Ramadan 2026</h2>
                    <p className="text-white/60 text-xs mt-1">{userName || 'A Blessed Soul'}</p>
                  </div>

                  {/* Crescent + Stars decoration */}
                  <div className="flex justify-center items-center gap-2">
                    <Sparkles className="w-4 h-4 text-[var(--sr-vendor)]/40" />
                    <Moon className="w-8 h-8 text-[var(--sr-vendor)]" />
                    <Sparkles className="w-4 h-4 text-[var(--sr-vendor)]/40" />
                  </div>

                  {/* Stats Grid */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div className="bg-white/5 rounded-xl p-3 text-center">
                      <p className="text-[var(--sr-customer)] text-xl font-bold">{daysWithEntry}</p>
                      <p className="text-white/65 text-[10px]">Days Journaled</p>
                    </div>
                    <div className="bg-white/5 rounded-xl p-3 text-center">
                      <p className="text-[var(--sr-vendor)] text-xl font-bold">{totalEntries}</p>
                      <p className="text-white/65 text-[10px]">Entries Written</p>
                    </div>
                    <div className="bg-white/5 rounded-xl p-3 text-center">
                      <p className="text-[var(--sr-ai)] text-xl font-bold">{totalTags}</p>
                      <p className="text-white/65 text-[10px]">Tags Used</p>
                    </div>
                    <div className="bg-white/5 rounded-xl p-3 text-center">
                      <p className="text-[var(--sr-rider)] text-xl font-bold">{ramadanProgress}%</p>
                      <p className="text-white/65 text-[10px]">Consistency</p>
                    </div>
                  </div>

                  {/* Top Mood */}
                  {topMood && (
                    <div className="text-center">
                      <p className="text-white/60 text-xs">Your Ramadan Mood</p>
                      <p className="text-white text-sm font-medium capitalize flex items-center justify-center gap-1 mt-1">
                        {getMoodIcon(topMood[0] as Mood)}
                        {topMood[0]}
                      </p>
                    </div>
                  )}

                  {/* Progress Bar */}
                  <div>
                    <div className="flex justify-between text-[10px] text-white/65 mb-1">
                      <span>Ramadan Journey</span>
                      <span>{ramadanProgress}%</span>
                    </div>
                    <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${ramadanProgress}%` }}
                        transition={{ duration: 1, ease: 'easeOut' }}
                        className="h-full bg-gradient-to-r from-[var(--sr-customer)] via-[var(--sr-vendor)] to-[var(--sr-ai)] rounded-full"
                      />
                    </div>
                  </div>

                  {/* Footer */}
                  <div className="text-center">
                    <p className="text-white/20 text-[10px]">SwiftRamadan 🌙</p>
                  </div>
                </div>
              </div>

              {/* Actions */}
              <div className="p-4 border-t border-white/8 space-y-2">
                <button
                  onClick={() => {
                    toast({ title: 'Card saved! 🌙', description: 'Share your Ramadan journey with friends' });
                    setShowShareable(false);
                  }}
                  className="w-full bg-[var(--sr-customer)] text-black font-semibold py-2.5 rounded-xl flex items-center justify-center gap-2 hover:bg-[var(--sr-customer)]/90 transition-colors"
                >
                  <Share2 className="w-4 h-4" /> Share Card
                </button>
                <button
                  onClick={() => setShowShareable(false)}
                  className="w-full bg-white/5 text-white/50 py-2.5 rounded-xl text-sm hover:bg-white/10 transition-colors"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default React.memo(RamadanDiaryInner);
